name = "js-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "arcpanel"
database_id = "fee8843d-1fb5-463b-8532-9c44122ab1d5"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "arc-panel-secret-key-2024"
