name = "arcpanel"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "arcpanel"
database_id = "10627eab-1d99-40cb-a763-3637d204b468"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secret-key-change-this-123456789"

[site]
bucket = "./public"